[build] 
  publish = "." 
  functions = "netlify/functions"
  command = "npm install"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"
 
[dev] 
  publish = "." 
  functions = "netlify/functions" 
  port = 8888

[functions]
  node_bundler = "esbuild"